### ISSUE TITLE
CompanyDetailsPage

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/test___capstone-meinitjob#1]
#CompanyDetailsPage

##Value proposition

As a user, I want to see relevant information about the selected company displayed.

##Acceptance criteria

 - [x] Are the relevant information of the company easily and directly readable?
  - [x] There is a header with the name of the company.
 - [x]  Are the boxes/components that provide information about the company always displayed in the same order?
  - [x] The correct data for the selected company is displayed.

##Tasks

  - [x] Display all information about the company from the JSON file:
 - [x]  name (string)
 - [x]  location (string)
 - [x]  remote (boolean)
  - [x] revenue (integer)
  - [x] numberOfEmployee (integer)
  - [x] sector (string)
  - [x] established (integer)
 - [x]  homepage (string URL)
  - [x] description (string)
 - [x]  logo (string URL)
 - [x]  Include an h1 header with the name of the company.
 - [x]  Display the company's data using reusable CompanyDataBoxComponents.
  - [x] Create a CompanyDataBoxComponent with the following properties:
  - [x] heading (header of the box)
 - [x]  content (HTML/JSX text content of the box)

**Comment by rabe200** [comment]
lgtm
