### ISSUE TITLE
Auflistung der Arbeitgeber/Landingpage

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/test___capstone-meinitjob#2]
# Listing of Employers

## Value Proposition

As a user, I want to find an overview of potential employers on the landing page and be directed to the corresponding company detail views when clicked.

## Acceptance Criteria

- [x] Three companies should be displayed.
- [x] Each displayed company should show its logo and name.
- [x] Each company logo/name should be an href/link to its respective details page.
- [x] A button to be redirected to the overview page for all companies.

## Tasks
 
- [x] Render three elements from the JSON file.
- [x] Display a component with the name and logo of each company.
- [x] Create a CompanyPreview component with the following props: logo, name
- [x] Each click on the name/logoshould lead to the respective detail page.
- [x] Create a button for the overview page.
- [x] The button is clickable and leads to the overview page.

**Comment by AnjaSiewert** [comment]
A wireframe would be helpful to check the US
## Tasks
You could sum up task 2,3,4 & 5 to one: Create a `CompanyPreview` component with the following props: `name`, `logo`
In task 6 I would add each click **on the name/logo** leads to the respective details page, to make it clear since you also have a button that is clickable :)

**Comment by DominicWebDev** [comment]
thanks, check again
