### ISSUE TITLE
Rendern aller Unternehmen auf der CompanyPage

### ISSUE THREAD

**Issue by DominicWebDev** [DominicWebDev/test___capstone-meinitjob#3]
# Overview Companies

## Value Proposition

As a user, I want to have an overview of all companies listed on the platform.

## Acceptance Criteria

- [x] There is a header with the number of current companies.
- [x] the companies + their respective logos are displayed
- [x] Filter companies by size and remote work 
- [x] Clicking on a company redirect to its details page

## Tasks

- [x] Display the following information of the companies from the JSON file: logo (string URL)name (string)
- [x] Display an h4? with the name of each company and its corresponding logo.
- [x] Name and logo should be an href/link and lead to the details page.

**Comment by AnjaSiewert** [comment]
Same here, a wireframe would be nice :) 
## Acceptance criteria
They shouldn't be expressed in questions, preferably in statements
## Tasks
You can sum up Task 1-3 in one task

**Comment by DominicWebDev** [comment]
Done please check again
